title: Ticketing Reference Application
description: ASP.NET Core and Angular ticket management reference application

theme: minima

markdown: kramdown

plugins:
  - jekyll-seo-tag

collections: {}

defaults:
  -
    scope:
      path: ""
    values:
      layout: default